layout_spectrum: 0.09396229
typography_spectrum: 0.2314196
color:
  saturation: 0.04585122
  lightness: 0.1753875
  brandStrength: 0.4591502
  rhythmicContrast: 0.07020773
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Sebastian
